### ISSUE TITLE
withDB doc's say "The returned handle should be released with close."

### ISSUE THREAD

**Issue by unhammer** [jprupp/rocksdb-haskell#2]
https://hackage.haskell.org/package/rocksdb-haskell-jprupp-2.1.6/docs/Database-RocksDB.html#v:withDB 
typically `with`-functions do the closing for you. Is there a `close` function we should be calling, or are the docs wrong?

**Comment by jprupp** [comment]
It will be closed automatically when the `with` function it is out of scope.
