### ISSUE TITLE
Segmentation fault in GHC 9.6.6

### ISSUE THREAD

**Issue by prolic** [jprupp/rocksdb-haskell#8]
What versions of rocksdb do I need to use? I tried librocksdb-dev (from Ubuntu apt), and from source v8.9.1 and v9.8.4.

**Comment by prolic** [comment]
This library seems to be unmaintained.

**Comment by jprupp** [comment]
I've seen a segmentation fault happen with an older RocksDB library from the Debian repository. If I recall correctly it was version 7.8. Make sure you are linking to a newer version of the RocksDB libraries. I have this running in a high-traffic production environment with multiple threads right now without segmentation faults.

**Comment by prolic** [comment]
I suspect there might have been an error in how I was using the library, though I would have expected compilation errors rather than segmentation faults in that case.

After attempting three different rocksdb versions without success, I decided to switch to LMDB, which immediately solved my use case. Since I've now moved forward with a different solution, I won't be able to provide additional debugging information for this issue.

Please feel free to close this ticket. I appreciate the support.
